// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(opts) {
    return function(v) {
      v.set('hide', function(model, ns) {
        if (model != null) {
          model.tigger('hide', ns);
          return model.hidden = true;
        } else {
          return this.$el.hide();
        }
      });
      return v.set('show', function(model, ns) {
        if (model != null) {
          model.tigger('show', ns);
          return model.hidden = false;
        } else {
          return this.$el.show();
        }
      });
    };
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
