// Generated by CoffeeScript 1.6.3
(function() {
  var ap;

  ap = require('ap');

  module.exports = function(opts) {
    var template;
    template = opts.template;
    return function(v) {
      return v.set('render', function(cb) {
        var d, go, model,
          _this = this;
        ap = ap.bind(this);
        go = function(html) {
          _this.$el.html(html);
          return typeof cb === "function" ? cb(_this) : void 0;
        };
        d = {};
        if (opts != null ? opts.model : void 0) {
          model = ap(opts.model);
        } else {
          model = this.model;
        }
        if (ap(opts.raw) != null) {
          d.model = model;
        } else {
          d.model = model.toJSON();
        }
        if (ap(opts.extra)) {
          _(d).extend(ap(opts.extra));
        }
        if (ap(opts.async)) {
          return template(d, go);
        } else {
          return go(ap(template(d)));
        }
      });
    };
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
