// Generated by CoffeeScript 1.6.2
(function() {
  var Build, BuildSchema, ObjectId, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  BuildSchema = new Schema({
    buildNumber: Number,
    project: String,
    commit: String,
    author: String,
    createdOn: {
      type: Date,
      "default": Date.now()
    },
    completedOn: {
      type: Date,
      "default": Date.now()
    },
    status: {
      type: String,
      "enum": ['success', 'failed']
    }
  });

  Build = mongoose.model('Build', BuildSchema);

  module.exports = Build;

}).call(this);

/*
//@ sourceMappingURL=build.map
*/
