// Generated by CoffeeScript 1.6.2
(function() {
  var Build, body, fs, indexCtrl, path, _;

  fs = require('fs');

  path = require('path');

  _ = require('underscore')._;

  Build = require('../models/build');

  body = require('connect').bodyParser();

  indexCtrl = function(app, jobs) {
    app.get('/', function(req, res) {
      return res.render("index", {
        title: "Simplex"
      });
    });
    app.post('/trigger', body, function(req, res) {
      var q;

      body = req.body;
      q = Build.findOne();
      q.sort({
        buildNumber: -1
      }).limit(1);
      return q.exec(function(err, build) {
        var num;

        console.log(build);
        if (build != null) {
          num = build.buildNumber + 1;
        } else {
          num = 0;
        }
        jobs.create('build', {
          title: 'Build #' + num,
          settings: app.config,
          body: body,
          buildNum: num
        }).save();
        return res.json(200, 'recieved');
      });
    });
    app.get('/populateBuilds', function(req, res) {
      var build, done, i, ret, status, _i, _results;

      ret = function(msg) {
        return res.json(200, msg);
      };
      done = _.after(25, ret);
      _results = [];
      for (i = _i = 1; _i <= 25; i = ++_i) {
        if (Math.floor(Math.random() * 10) % 2 === 0) {
          status = "success";
        } else {
          status = "failed";
        }
        build = new Build({
          buildNumber: i,
          project: "test",
          commit: '123' + i + '',
          author: 'Garrett',
          status: status
        }).save();
        _results.push(done('completed'));
      }
      return _results;
    });
    return app.get('/builds', body, function(req, res) {
      return Build.find(function(err, builds) {
        builds = _(builds).map(function(b) {
          return b.toObject();
        });
        return res.json(200, builds);
      });
    });
  };

  module.exports.init = function(app, jobs) {
    return indexCtrl(app, jobs);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
