// Generated by CoffeeScript 1.6.3
var collection, mkDashboardView, render;

collection = require('collection');

render = require('render');

mkDashboardView = function(config) {
  var v;
  if (config == null) {
    config = {};
  }
  v = bQuery.view();
  v.init(function(opts) {
    if (opts == null) {
      opts = {};
    }
    return console.log('dashboard opts: ', opts);
  });
  v.use(render({
    template: require('../../templates').dashboard,
    model: function() {
      return {
        build: 'hi'
      };
    },
    raw: true
  }));
  return v.make();
};

module.exports = mkDashboardView;
