// Generated by CoffeeScript 1.6.3
var Dashboard, DashboardCollection, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Dashboard = require('./model');

DashboardCollection = (function(_super) {
  __extends(DashboardCollection, _super);

  function DashboardCollection() {
    _ref = DashboardCollection.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  DashboardCollection.prototype.model = Dashboard;

  DashboardCollection.prototype.initialize = function(opts) {
    if (opts == null) {
      opts = {};
    }
  };

  DashboardCollection.prototype.url = '/dashboard';

  return DashboardCollection;

})(Backbone.Collection);

module.exports = DashboardCollection;
