// Generated by CoffeeScript 1.6.3
var ex, view, views, _i, _len;

ex = module.exports;

views = ["dashboard"];

ex.views = {};

for (_i = 0, _len = views.length; _i < _len; _i++) {
  view = views[_i];
  ex.views[view] = require("./views/" + view);
}

ex.collection = require('./collection');

ex.model = require('./model');
