// Generated by CoffeeScript 1.6.3
var Dashboard, querystring, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

querystring = require('querystring');

Dashboard = (function(_super) {
  __extends(Dashboard, _super);

  function Dashboard() {
    _ref = Dashboard.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Dashboard.prototype.idAttribute = "_id";

  Dashboard.prototype.urlRoot = '/dashboard';

  Dashboard.prototype.initialize = function(props) {
    if (props == null) {
      props = {};
    }
  };

  return Dashboard;

})(Backbone.Model);

module.exports = Dashboard;
